sudo: required
dist: trusty

language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

script:
  - (cd libcgroup-sys && cargo test --verbose)
  - (cd libcgroup && sudo cargo test --verbose --features=sudo)
