[package]
name = "rcm"
version = "0.1.0"
authors = ["Jimmi Dyson <jimmidyson@gmail.com>"]

[workspace]
members = [
  "libcgroup-sys",
  "libcgroup",
]

[dependencies]
log = "0.3"
libcgroup = { path = "libcgroup", version = "0.2"}
